# Netlify Configuration for R_SIM Rocket Simulation Platform
# Frontend-only hosting with Supabase + Google Cloud backend

[build]
  # Build command for React frontend
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"
  
  # Directory where the built files are located
  publish = "frontend/dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Supabase configuration (will be set in Netlify dashboard)
  VITE_SUPABASE_URL = "https://ovwgplglypjfuqsflyhc.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92d2dwbGdseXBqZnVxc2ZseWhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyOTQ0MDgsImV4cCI6MjA3Mjg3MDQwOH0.YTjAKmshWQ5rFG9an2de8UHu9NA-03U8B6km8XLmjC0"
  
  # Google Cloud Function URL (update with your deployed function)
  VITE_GCP_FUNCTION_URL = "https://us-central1-centered-scion-471523-a4.cloudfunctions.net/rocket-cfd-simulator"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API proxy (if needed for CORS)
# API redirects for simulation endpoints
[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/simulation"
  status = 200
  force = true
  headers = { X-From = "Netlify" }

[[redirects]]
  from = "/api/simulation/start"
  to = "/.netlify/functions/simulation"
  status = 200
  force = true
  headers = { X-From = "Netlify" }
