# Render deployment configuration for R_SIM Rocket Simulation Platform
services:
  - type: web
    name: rocket-sim-backend
    env: python
    plan: starter  # Free tier
    buildCommand: |
      pip install -r backend/requirements.txt
    startCommand: python backend/f_backend.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: PORT
        value: 5000
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /api/simulation/status
    disk:
      name: simulation-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

  - type: web
    name: rocket-sim-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://rocket-sim-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
