# Render deployment configuration for R_SIM Rocket Simulation Platform
# Note: Heavy CFD simulations run on Google Cloud Functions, not Render
# Storage is handled by Supabase, not Render
services:
  - type: web
    name: rocket-sim-backend
    env: python
    plan: starter  # Free tier - only handles web API, not CFD
    buildCommand: |
      pip install -r backend/requirements.txt
    startCommand: python backend/f_backend.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: PORT
        value: 5000
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: SIMULATION_MODE
        value: cloud  # Forces use of Google Cloud Functions for CFD
    healthCheckPath: /api/health

  - type: web
    name: rocket-sim-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://rocket-sim-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
