# Render deployment configuration for R_SIM Rocket Simulation Platform
# Note: Heavy CFD simulations run on Google Cloud Functions, not Render
# Storage is handled by Supabase, not Render
services:
  - type: web
    name: r-sim
    env: python
    plan: starter  # Free tier - only handles web API, not CFD
    buildCommand: |
      # Install Node.js for frontend build
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      # Install Python dependencies
      pip install -r backend/requirements.txt
      # Build frontend
      cd frontend
      npm install
      npm run build
      cd ..
    startCommand: python backend/f_backend.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: PORT
        value: 5000
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: SIMULATION_MODE
        value: cloud  # Forces use of Google Cloud Functions for CFD
    healthCheckPath: /api/health
